#!/usr/bin/env python3
"""
Build script to generate _git_info.py with current git metadata.
This should be run before packaging/building.
"""

import subprocess
from pathlib import Path


def get_git_info():
    try:
        sha = subprocess.check_output(
            ["git", "rev-parse", "HEAD"], stderr=subprocess.DEVNULL, text=True
        ).strip()

        status = subprocess.check_output(
            ["git", "status", "--porcelain"], stderr=subprocess.DEVNULL, text=True
        )
        dirty = bool(status.strip())
        return sha, dirty
    except Exception:
        return None, None


def main():
    root = Path(__file__).parent.parent
    target = root / "src" / "pytest_llm_report" / "_git_info.py"

    sha, dirty = get_git_info()

    content = f"""# Generated by scripts/build_git_info.py
GIT_SHA = {repr(sha)}
GIT_DIRTY = {dirty}
"""

    print(f"Writing git info to {target}...")
    target.write_text(content, encoding="utf-8")
    print(f"SHA: {sha}, Dirty: {dirty}")


if __name__ == "__main__":
    main()
